//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Demolan5.Module.Demolan5
{

    [DefaultProperty("Nam")]
    public partial class Bangluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"BangluongReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        int fNam;
        [DevExpress.Xpo.DisplayName(@"Năm")]
        public int Nam
        {
            get { return fNam; }
            set { SetPropertyValue<int>(nameof(Nam), ref fNam, value); }
        }
        int fThang;
        [DevExpress.Xpo.DisplayName(@"Tháng")]
        public int Thang
        {
            get { return fThang; }
            set { SetPropertyValue<int>(nameof(Thang), ref fThang, value); }
        }
        int fSogio;
        [DevExpress.Xpo.DisplayName(@"Số giờ làm việc")]
        public int Sogio
        {
            get { return fSogio; }
            set { SetPropertyValue<int>(nameof(Sogio), ref fSogio, value); }
        }
        decimal fLuong;
        [DevExpress.Xpo.DisplayName(@"Lương")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal Luong
        {
            get { return fLuong; }
            set { SetPropertyValue<decimal>(nameof(Luong), ref fLuong, value); }
        }
    }

}
