//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Demolan5.Module.Demolan5
{

    [DefaultProperty("Soban")]
    public partial class Hoadon : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Khachhang fKhachID;
        [Association(@"HoadonReferencesKhachhang")]
        public Khachhang KhachID
        {
            get { return fKhachID; }
            set { SetPropertyValue<Khachhang>(nameof(KhachID), ref fKhachID, value); }
        }
        Nhanvien fNhanvienID;
        [Association(@"HoadonReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        int fSoban;
        [DevExpress.Xpo.DisplayName(@"Số bàn")]
        public int Soban
        {
            get { return fSoban; }
            set { SetPropertyValue<int>(nameof(Soban), ref fSoban, value); }
        }
        DateTime fNgay;
        [DevExpress.Xpo.DisplayName(@"Ngày xuất hóa đơn")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        int fSo;
        [DevExpress.Xpo.DisplayName(@"Số hóa đơn")]
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int So
        {
            get { return fSo; }
            set { SetPropertyValue<int>(nameof(So), ref fSo, value); }
        }

        [DevExpress.Xpo.DisplayName(@"Tổng tiền")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]
        public decimal TongTien 
        {
            get 
            {
                decimal tien = 0;
                foreach(HoadonCT item in HoadonCTs)
                {
                    tien += item.Thanhtien;
                }
                return tien;
            }
        }
        [Association(@"HoadonCTReferencesHoadon"), Aggregated]
        public XPCollection<HoadonCT> HoadonCTs { get { return GetCollection<HoadonCT>(nameof(HoadonCTs)); } }
    }

}
