//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Demolan5.Module.Demolan5
{

    [DefaultProperty("Soluong")]
    public partial class HoadonCT : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Hoadon fHoadonID;
        [Association(@"HoadonCTReferencesHoadon")]
        public Hoadon HoadonID
        {
            get { return fHoadonID; }
            set { SetPropertyValue<Hoadon>(nameof(HoadonID), ref fHoadonID, value); }
        }
        Sanpham fSanphamID;
        [Association(@"HoadonCTReferencesSanpham")]
        public Sanpham SanphamID
        {
            get { return fSanphamID; }
            set 
            {
                if (SetPropertyValue<Sanpham>(nameof(SanphamID), ref fSanphamID, value)
                    && !IsLoading && !IsDeleted && value != null)
                    Dongia = value.Giaban;
            }
        }
        double fSoluong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public double Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<double>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        [DevExpress.Xpo.DisplayName(@"Đơn giá")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal Thanhtien
        {
            get { return (decimal)(EvaluateAlias(nameof(Thanhtien))); }
        }   
        [Association(@"TieuhaoReferencesHoadonCT"), Aggregated]
        public XPCollection<Tieuhao> Tieuhaos { get { return GetCollection<Tieuhao>(nameof(Tieuhaos)); } }
    }

}
