//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Demolan5.Module.Demolan5
{

    [DefaultProperty("Hoten")]
    public partial class Nhacungcap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHoten;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Họ và tên")]
        public string Hoten
        {
            get { return fHoten; }
            set { SetPropertyValue<string>(nameof(Hoten), ref fHoten, value); }
        }
        string fDienthoai;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Điện thoại")]
        public string Dienthoai
        {
            get { return fDienthoai; }
            set { SetPropertyValue<string>(nameof(Dienthoai), ref fDienthoai, value); }
        }
        int fMST;
        [DevExpress.Xpo.DisplayName(@"Mã số thuế")]
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int MST
        {
            get { return fMST; }
            set { SetPropertyValue<int>(nameof(MST), ref fMST, value); }
        }
        [Association(@"PhieunhapReferencesNhacungcap"), Aggregated]
        public XPCollection<Phieunhap> Phieunhaps { get { return GetCollection<Phieunhap>(nameof(Phieunhaps)); } }
        [Association(@"PhieuchiReferencesNhacungcap"), Aggregated]
        public XPCollection<Phieuchi> Phieuchis { get { return GetCollection<Phieuchi>(nameof(Phieuchis)); } }
    }

}
