//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Demolan5.Module.Demolan5
{

    [DefaultProperty("TenNhom")]
    public partial class NhomSP : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fTenNhom;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Tên nhóm")]
        public string TenNhom
        {
            get { return fTenNhom; }
            set { SetPropertyValue<string>(nameof(TenNhom), ref fTenNhom, value); }
        }
        int fPhanloai;
        [DevExpress.Xpo.DisplayName(@"Phân loại")]
        public int Phanloai
        {
            get { return fPhanloai; }
            set { SetPropertyValue<int>(nameof(Phanloai), ref fPhanloai, value); }
        }
        [Association(@"SanphamReferencesNhomSP"), Aggregated]
        public XPCollection<Sanpham> Sanphams { get { return GetCollection<Sanpham>(nameof(Sanphams)); } }
    }

}
