//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Demolan5.Module.Demolan5
{

    [DefaultProperty("So")]
    public partial class Phieuchi : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"PhieuchiReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        Nhacungcap fNCCID;
        [Association(@"PhieuchiReferencesNhacungcap")]
        public Nhacungcap NCCID
        {
            get { return fNCCID; }
            set { SetPropertyValue<Nhacungcap>(nameof(NCCID), ref fNCCID, value); }
        }
        int fSo;
        [DevExpress.Xpo.DisplayName(@"Số phiếu")]
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int So
        {
            get { return fSo; }
            set { SetPropertyValue<int>(nameof(So), ref fSo, value); }
        }
        DateTime fNgay;
        [DevExpress.Xpo.DisplayName(@"Ngày lập phiếu chi")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        decimal fSotien;
        [DevExpress.Xpo.DisplayName(@"Số tiền")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal Sotien
        {
            get { return fSotien; }
            set { SetPropertyValue<decimal>(nameof(Sotien), ref fSotien, value); }
        }
    }

}
